-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.14.0.75.2
-- Module  Version: 5.7
-- Sat Nov 23 08:30:37 2024

-- parameterized module component declaration
component pll
    port (CLK: in std_logic; CLKOP: out std_logic; LOCK: out std_logic);
end component;

-- parameterized module component instance
__ : pll
    port map (CLK=>__, CLKOP=>__, LOCK=>__);
